# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

#variables:
#  tag: 'Set by Powershell script'
#   tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool: 
      name: Redshift-OnPrem-Linux
      vmImage: 'ubuntu-latest'
    steps:
#    - task: PowerShell@2
#      displayName: Set the VersionNumber variable value
#      inputs:
#        targetType: 'inline'
#        script: |
#          [string] $dateTime = (Get-Date -Format 'yyyyMMdd.HHmmss')
#          Write-Host "##vso[task.setvariable variable=tag]$dateTime"
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub-awesomejack295'
        repository: 'awesomejack295/kubecraftadmin'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest